#!/usr/bin/env python3
import sys


try:
    from charmhelpers.core import host, hookenv, unitdata
    from jujubigdata import utils
    charm_ready = True
except ImportError:
    charm_ready = False

if not charm_ready:
    from subprocess import call
    call(['action-fail', 'HBase service not yet ready'])
    sys.exit(1)

if not host.service_available('hbase-regionserver') or \
   not host.service_available('hbase-thrift'):
    from subprocess import call
    call(['action-fail', 'HBase regionserver/thrift not available'])
    sys.exit(1)

host.service_stop('hbase-regionserver')
host.service_stop('hbase-thrift')
