options:
  ha_setup:
    default: false
    type: boolean
    description: Set to true if this is an HA deployment.
  auto_failover:
    default: true
    type: boolean
    description: Set to true if in this HA deployment we want automatic failover.
