#!/usr/bin/python3

import unittest
import amulet


class TestDeploy(unittest.TestCase):
    """
    Deployment test for Apache Zookkepper quorum
    """

    @classmethod
    def setUpClass(cls):
        cls.d = amulet.Deployment(series='trusty')

        cls.d.add('jdk', charm='openjdk')
        cls.d.add('zookeeper', charm='hadoop-zookeeper', units=3)
        cls.d.relate('zookeeper:java', 'jdk:java')

        cls.d.setup(timeout=900)
        cls.d.sentry.wait(timeout=1800)
        cls.unit = cls.d.sentry['zookeeper'][0]

    def test_deploy(self):
        output, retcode = self.unit.run("pgrep -a java")
        assert 'QuorumPeerMain' in output, "zookeeper QuorumPeerMain daemon is not started"

    def test_quorum(self):
        '''
        Verify that our peers are talking to each other, and taking on
        appropriate roles.

        '''
        output, retcode = self.unit.run("/usr/lib/zookeeper/bin/zkServer.sh status")
        # Unit should be a leader or follower
        self.assertTrue("leader" in output or "follower" in output)


if __name__ == '__main__':
    unittest.main()
